//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESP8266_DatabaseAccess.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_esp_temp_humedad
    {
        public int idTempHumedad { get; set; }
        public float temperatura { get; set; }
        public float humedad { get; set; }
        public int idNode { get; set; }
        public System.DateTime horaFecha { get; set; }
    }
}
