//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESP8266_DatabaseAccess.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_esp_node
    {
        public int idNode { get; set; }
        public string chipInfo { get; set; }
        public string flashInfo { get; set; }
        public string alias { get; set; }
        public bool isActive { get; set; }
    }
}
