//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESP8266.Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_pin
    {
        public int PinNumber { get; set; }
        public bool IsDigital { get; set; }
        public float Value { get; set; }
        public Nullable<bool> State { get; set; }
        public int IdNode { get; set; }
    
        public virtual t_node t_node { get; set; }
    }
}
