//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESP8266_Database.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_node
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_node()
        {
            this.t_temp_humedad = new HashSet<t_temp_humedad>();
        }
    
        public int IdNode { get; set; }
        public string ChipInfo { get; set; }
        public string FlashInfo { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_temp_humedad> t_temp_humedad { get; set; }
    }
}
